/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import ventanas.DialogoClientes.DialogoClientesAdd;
import clases.TablaLineasCl;
import clases.TablaLineasPr;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JPanel;
import ventanas.DialogoProductos.DialogoProductosAdd;

/**
 *
 * @author Wiku
 */
public class PanelProductos extends javax.swing.JPanel {

    Connection connection;

    public PanelProductos(Connection connection) {
        this.connection = connection;
        initComponents();
        int colork=0;
        ArrayList<ArrayList<String>> datosmetodo = new ArrayList();
        datosmetodo = mostrardatos();
        //Añadir labels al scroll
        //System.out.println("ready to index");
        //System.out.println(datosmetodo.size());
        if (datosmetodo.size() > 0) {
            //System.out.println(datosmetodo.get(0).size()+"aaaaaaaaaaa");

            //TODO esta vacio el array
            for (ArrayList<String> dato : datosmetodo) {

                if (dato.size() > 0) {
                    panelLabels.add(new TablaLineasPr(dato.get(0), dato.get(1), dato.get(2), dato.get(3), dato.get(4), 
                            dato.get(5), connection, panelLabels,colork));
                    colork++;
                }
                
            }
        }for (int i = panelLabels.getComponentCount(); i < 10; i++) {
                    panelLabels.add(new JPanel()).setBackground(new Color(204,255,255));
                }

    }

    private ArrayList<ArrayList<String>> mostrardatos() {
        String sql = "SELECT ROWID,* FROM productos";
        Statement st;
        ArrayList<ArrayList<String>> datosmetodo = new ArrayList();

        for (ArrayList<String> dato : datosmetodo) {
            //datos.add(new ArrayList());
        }
        try {
            st = connection.createStatement();
            ResultSet result = st.executeQuery(sql);
            int i = 0;
            while (result.next()) {
                datosmetodo.add(new ArrayList());
                datosmetodo.get(i).add(result.getString(1));
                datosmetodo.get(i).add(result.getString(2));
                datosmetodo.get(i).add(result.getString(3));
                datosmetodo.get(i).add(result.getString(4));
                datosmetodo.get(i).add(result.getString(5));
                datosmetodo.get(i).add(result.getString(6));
                i++;

            }
        } catch (SQLException ex) {
            System.out.println("ex");
            System.out.println("error");
            ex.printStackTrace();

        }
        return datosmetodo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelLabels = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelDefaukt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        delete.setText("jMenuItem1");
        jPopupMenu1.add(delete);

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1115, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelLabels.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(panelLabels);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1110, 490));

        jButton1.setText("Añadir Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 270, 50));

        panelDefaukt.setBackground(new java.awt.Color(204, 255, 255));
        panelDefaukt.setForeground(new java.awt.Color(204, 255, 255));
        panelDefaukt.setLayout(new java.awt.GridLayout(0, 4));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre Producto");
        panelDefaukt.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Precio producto/Unidad");
        panelDefaukt.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("I.v.a aplicable");
        panelDefaukt.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha Añadido");
        panelDefaukt.add(jLabel4);

        add(panelDefaukt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1110, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Base datos productos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 530, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogoProductosAdd dialogoClientesAdd = new DialogoProductosAdd(new javax.swing.JDialog(), true, connection, panelLabels);
        dialogoClientesAdd.setVisible(true);
  
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDefaukt;
    private javax.swing.JPanel panelLabels;
    // End of variables declaration//GEN-END:variables
}
