/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Wiku
 */
public class Principal extends javax.swing.JFrame {

    Color entrada = new Color(102, 255, 153);
    Color salida = new Color(204, 255, 204);
    Color oldsalida = new Color(214, 217, 223);
    GridBagLayout dinLayout = new GridBagLayout();
    PanelClientes panelClientes;
    PanelFacturas panelFacturas;
    PanelInicio panelInicio;
    PanelUsers panelUsers;
    PanelProductos panelProductos;
    PanelPresupuesto panelPresupuesto;
    Connection connection;

    public Principal() {
        //URLBasededatosApp
        String url = "jdbc:sqlite:src/res/bd/Presudy.db";
        //Conexion a base de datos
        //Se conecta a la bd interna
        try {
            connection = DriverManager.getConnection(url);
        } catch (Exception ex) {
            System.out.println("error conexion bd");
            ex.printStackTrace();
        }
        initComponents();
        panelClientes = new PanelClientes(connection);
        panelFacturas = new PanelFacturas(connection);
        panelInicio = new PanelInicio();
        panelProductos = new PanelProductos(connection);
        panelPresupuesto = new PanelPresupuesto(connection);
        panelUsers = new PanelUsers(connection);
        PanelDinamico.setLayout(dinLayout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelInicio, c);
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelFacturas, c);
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelClientes, c);
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelProductos, c);
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelPresupuesto);
        c.gridx = 0;
        c.gridy = 0;
        PanelDinamico.add(panelUsers);
        c.gridx = 0;
        c.gridy = 0;
        panelInicio.setVisible(true);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(false);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(false);
        //Icono aplicación
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClass().getResource("/res/iconos/inicio.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDinamico = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Factura = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Presupuestos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Productos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Users = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PanelSeparador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelDinamico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDinamicoLayout = new javax.swing.GroupLayout(PanelDinamico);
        PanelDinamico.setLayout(PanelDinamicoLayout);
        PanelDinamicoLayout.setHorizontalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        PanelDinamicoLayout.setVerticalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelOpciones.setBackground(new java.awt.Color(204, 255, 204));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setBackground(new java.awt.Color(204, 255, 204));
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/inicio.png"))); // NOI18N
        jLabel4.setText("Inicio");
        Inicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        Factura.setBackground(new java.awt.Color(204, 255, 204));
        Factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FacturaMouseExited(evt);
            }
        });
        Factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/factura.png"))); // NOI18N
        jLabel5.setText("Factura");
        Factura.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 60));

        Clientes.setBackground(new java.awt.Color(204, 255, 204));
        Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientesMouseExited(evt);
            }
        });
        Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/cliente.png"))); // NOI18N
        jLabel6.setText("Clientes");
        Clientes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 160, 60));

        Presupuestos.setBackground(new java.awt.Color(204, 255, 204));
        Presupuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Presupuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresupuestosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PresupuestosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PresupuestosMouseExited(evt);
            }
        });
        Presupuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/presupuesto.png"))); // NOI18N
        jLabel8.setText("Presupuesto");
        Presupuestos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Presupuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 60));

        Productos.setBackground(new java.awt.Color(204, 255, 204));
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosMouseExited(evt);
            }
        });
        Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/producst.png"))); // NOI18N
        jLabel10.setText("Productos");
        Productos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 160, 60));

        Users.setBackground(new java.awt.Color(204, 255, 204));
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsersMouseExited(evt);
            }
        });
        Users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconos/user.png"))); // NOI18N
        jLabel9.setText("Usuarios");
        Users.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        PanelOpciones.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 160, 60));

        PanelSeparador.setBackground(new java.awt.Color(0, 0, 0));
        PanelSeparador.setForeground(new java.awt.Color(0, 0, 0));
        PanelSeparador.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout PanelSeparadorLayout = new javax.swing.GroupLayout(PanelSeparador);
        PanelSeparador.setLayout(PanelSeparadorLayout);
        PanelSeparadorLayout.setHorizontalGroup(
            PanelSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        PanelSeparadorLayout.setVerticalGroup(
            PanelSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelSeparador, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(PanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseEntered
        Inicio.setBackground(entrada);
    }//GEN-LAST:event_InicioMouseEntered

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited
        Inicio.setBackground(salida);
    }//GEN-LAST:event_InicioMouseExited

    private void FacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseEntered
        Factura.setBackground(entrada);

    }//GEN-LAST:event_FacturaMouseEntered

    private void PresupuestosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresupuestosMouseEntered
        Presupuestos.setBackground(entrada);
    }//GEN-LAST:event_PresupuestosMouseEntered

    private void ProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseEntered
        Productos.setBackground(entrada);
    }//GEN-LAST:event_ProductosMouseEntered

    private void FacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseExited
        Factura.setBackground(salida);

    }//GEN-LAST:event_FacturaMouseExited

    private void PresupuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresupuestosMouseExited
        Presupuestos.setBackground(salida);
    }//GEN-LAST:event_PresupuestosMouseExited

    private void ProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseExited
        Productos.setBackground(salida);
    }//GEN-LAST:event_ProductosMouseExited

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        panelInicio.setVisible(true);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(false);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(false);

    }//GEN-LAST:event_InicioMouseClicked

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
        panelInicio.setVisible(false);
        panelFacturas.setVisible(true);
        panelClientes.setVisible(false);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(false);

       }//GEN-LAST:event_FacturaMouseClicked

    private void PresupuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresupuestosMouseClicked
        panelInicio.setVisible(false);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(false);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(true);
        panelUsers.setVisible(false);
        PanelPresupuesto.actualizartablas();

       }//GEN-LAST:event_PresupuestosMouseClicked

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        panelInicio.setVisible(false);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(false);
        panelProductos.setVisible(true);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(false);

       }//GEN-LAST:event_ProductosMouseClicked

    private void ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseExited
        Clientes.setBackground(salida);
    }//GEN-LAST:event_ClientesMouseExited

    private void ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseEntered
        Clientes.setBackground(entrada);
    }//GEN-LAST:event_ClientesMouseEntered

    private void ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseClicked
        panelInicio.setVisible(false);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(true);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(false);
    }//GEN-LAST:event_ClientesMouseClicked

    private void UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseClicked

        panelInicio.setVisible(false);
        panelFacturas.setVisible(false);
        panelClientes.setVisible(false);
        panelProductos.setVisible(false);
        panelPresupuesto.setVisible(false);
        panelUsers.setVisible(true);
    }//GEN-LAST:event_UsersMouseClicked

    private void UsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseEntered
        Users.setBackground(entrada);

    }//GEN-LAST:event_UsersMouseEntered

    private void UsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseExited
        Users.setBackground(salida);
    }//GEN-LAST:event_UsersMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Factura;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel PanelDinamico;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelSeparador;
    private javax.swing.JPanel Presupuestos;
    private javax.swing.JPanel Productos;
    private javax.swing.JPanel Users;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
